### ISSUE TITLE
iOS端的闪退问题又出现了

### ISSUE THREAD

**Issue by jiut** [honjow/FEhViewer#172]
版本：v1.2.79+479
现象同#126 ，日志如下：
```
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   TabViewController.firstLoad (package:fehviewer/pages/tab/controller/tabview_controller.dart:96)
│ #1   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ [E] HttpException{_message: HandshakeException: Connection terminated during handshake, _code: null, _data: null}
│ [E] #0      getGallery (package:fehviewer/network/request.dart:145)
│ [E] <asynchronous suspension>
│ [E] #1      SearchFetchListClient.fetch (package:fehviewer/pages/tab/fetch_list.dart:56)
│ [E] <asynchronous suspension>
│ [E] #2      CustomSubListController.fetchData (package:fehviewer/pages/tab/controller/tabbar/custom_sublist_controller.dart:127)
│ [E] <asynchronous suspension>
│ [E] #3      TabViewController.firstLoad (package:fehviewer/pages/tab/controller/tabview_controller.dart:82)
│ [E] <asynchronous suspension>
│ [E] #4      CustomSubListController.firstLoad (package:fehviewer/pages/tab/controller/tabbar/custom_sublist_controller.dart:40)
│ [E] <asynchronous suspension>
│ [E] 
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   TabViewController.firstLoad (package:fehviewer/pages/tab/controller/tabview_controller.dart:96)
│ #1   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ [E] HttpException{_message: HandshakeException: Connection terminated during handshake, _code: null, _data: null}
│ [E] #0      getGallery (package:fehviewer/network/request.dart:145)
│ [E] <asynchronous suspension>
│ [E] #1      SearchFetchListClient.fetch (package:fehviewer/pages/tab/fetch_list.dart:56)
│ [E] <asynchronous suspension>
│ [E] #2      CustomSubListController.fetchData (package:fehviewer/pages/tab/controller/tabbar/custom_sublist_controller.dart:127)
│ [E] <asynchronous suspension>
│ [E] #3      TabViewController.firstLoad (package:fehviewer/pages/tab/controller/tabview_controller.dart:82)
│ [E] <asynchronous suspension>
│ [E] #4      CustomSubListController.firstLoad (package:fehviewer/pages/tab/controller/tabbar/custom_sublist_controller.dart:40)
│ [E] <asynchronous suspension>
│ [E] 
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   TabViewController.firstLoad (package:fehviewer/pages/tab/controller/tabview_controller.dart:96)
│ #1   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ [E] HttpException{_message: null, _code: null, _data: null}
│ [E] #0      getGallery (package:fehviewer/network/request.dart:145)
│ [E] <asynchronous suspension>
│ [E] #1      SearchFetchListClient.fetch (package:fehviewer/pages/tab/fetch_list.dart:56)
│ [E] <asynchronous suspension>
│ [E] #2      CustomSubListController.fetchData (package:fehviewer/pages/tab/controller/tabbar/custom_sublist_controller.dart:127)
│ [E] <asynchronous suspension>
│ [E] #3      TabViewController.firstLoad (package:fehviewer/pages/tab/controller/tabview_controller.dart:82)
│ [E] <asynchronous suspension>
│ [E] #4      CustomSubListController.firstLoad (package:fehviewer/pages/tab/controller/tabbar/custom_sublist_controller.dart:40)
│ [E] <asynchronous suspension>
│ [E] 
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by ZhangQingsen** [comment]
桌面版也闪退

log如下，看着是文件夹被拒绝访问，我尝试用管理员模式运行也不行

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   CacheController._getTotalSizeOfFilesInDir (package:fehviewer/common/controller/cache_controller.dart:110)
│ #1   CacheController._getTotalSizeOfFilesInDir (package:fehviewer/common/controller/cache_controller.dart:105)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ [E] FileSystemException: Directory listing failed, path = 'C:\Users\Username\AppData\Local\Temp\msdtadmin\*' (OS Error: 拒绝访问。
│ [E] , errno = 5)
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
